apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-head
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-head
  template:
    metadata:
      labels:
        app: ray-head
    spec:
      containers:
      - name: ray-head
        image: rayproject/ray:latest
        command: ["ray", "start", "--head"]
        volumeMounts:
        - name: app-code
          mountPath: /samples
      volumes:
      - name: app-code
        configMap:
          name: my-app-code